= Configuration

Inferencium configuration files.

== Licensing
All content is licensed under https://git.inferencium.net/Inferencium/cfg/src/branch/stable/license/BSD-3-Clause-Clear.txt[BSD 3 Clause Clear]
license*. +
 +
*Excluding Linux configuration file(s), which are licensed under https://git.inferencium.net/Inferencium/cfg/src/branch/stable/license/GPL-2.0-only.txt[GPL v2]
license.

== Security
All files are checked for security issues; however, it is always the user's responsibility to
audit the code before installing and/or executing it. +
 +
Inferencium takes no responsibility for any security issues which may arise due to usage of this
repository.

== Branches

=== https://git.inferencium.net/Inferencium/cfg/src/branch/main/[main] +
Configuration files root directory files pre-alpha development and alpha testing occurs in this
branch. +
Feature-complete modifications of this branch are merged to beta branch for beta testing.

=== https://git.inferencium.net/Inferencium/cfg/src/branch/desktop/[desktop] +
Desktop configuration files pre-alpha development and alpha testing occurs in this branch. +
Feature-complete modifications of this branch are merged to beta branch for beta testing.

=== https://git.inferencium.net/Inferencium/cfg/src/branch/server/[server] +
Server configuration files pre-alpha development and alpha testing occurs in this branch. +
Feature-complete modifications of this branch are merged to beta branch for beta testing.

=== https://git.inferencium.net/Inferencium/cfg/src/branch/license/[license] +
Configuration files license files pre-alpha and alpha testing occurs in this branch. +
Feature-complete modifications of this branch are merged to beta branch for beta testing.

=== https://git.inferencium.net/Inferencium/cfg/src/branch/beta/[beta] +
Feature-complete beta testing of merged code from development branches occurs in this branch. +
Merges from development branches to this branch are squashed, and the updated versions of the
individual files are mentioned in the commit messages.

=== https://git.inferencium.net/Inferencium/cfg/src/branch/stable/[stable] +
Feature-complete and tested versions from beta branch are stored in this branch. +
Merges from beta branch to this branch are squashed, and the updated versions of the individual
files are mentioned in the commit messages. +
This branch contains code used in production.
